clusters:
  us-east-1:
    total_machines: 128
    guaranteed_machines: 30
    base_guaranteed: 1.00
    base_spot: 0.20
    sensitivity_g: 2.0
    sensitivity_s: 1.2
  eu-west-2:
    total_machines: 64
    guaranteed_machines: 40
    base_guaranteed: 1.10
    base_spot: 0.22
    sensitivity_g: 2.2
    sensitivity_s: 1.3
  ap-northeast-1:
    total_machines: 256
    guaranteed_machines: 10
    base_guaranteed: 0.90
    base_spot: 0.18
    sensitivity_g: 1.8
    sensitivity_s: 1.1